version: "3.8"

services:
    service_django:
        build: .
        container_name: service_django
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/service_django/
            - /var/log/service_django/:/var/log/service_django/
        ports:
            - "8001:8000"

